---
name: Appraisal Notify
on: [pull_request]

jobs:
  appraisal_notify:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
      - run: bundle install
